services:

  # MongoDB
  mongo-db:
    container_name: despliegue-db_mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/listas.js:/docker-entrypoint-initdb.d/listas.js:ro
    networks:
      - despliegue-network

     # NodeJS
  nodejs:
    container_name: despliegue-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      API_PORT: ${API_PORT}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - despliegue-network
    

networks:
  despliegue-network:
    driver: bridge